services:
  - type: web
    name: discord-bot-dashboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_PREFIX
        value: "!"
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: CALLBACK_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
